Student-Management-System/Models/EntityFramework/MARKS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARKS
    {
        public int MARKID { get; set; }
        public Nullable<int> STDID { get; set; }
        public Nullable<byte> LECTUREID { get; set; }
        public Nullable<byte> EXAM1 { get; set; }
        public Nullable<byte> EXAM2 { get; set; }
        public Nullable<byte> EXAM3 { get; set; }
        public Nullable<byte> PROJECT { get; set; }
        public Nullable<decimal> AVERAGE { get; set; }
        public Nullable<bool> SITUATION { get; set; }
    
        public virtual LECTURES LECTURES { get; set; }
        public virtual STUDENTS STUDENTS { get; set; }
    }
}

Student-Management-System/Controllers/MarkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentManagementSystem.Models.EntityFramework;
using StudentManagementSystem.Models;

namespace StudentManagementSystem.Controllers
{
    public class MarkController : Controller
    {
        // GET: Mark
        DbSchoolEntities db = new DbSchoolEntities();
        public ActionResult Index()
        {
            var marks = db.MARKS.ToList();
            return View(marks);
        }

        [HttpGet]
        public ActionResult NewMark()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NewMark(MARKS mrk)
        {
            db.MARKS.Add(mrk);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var mark = db.MARKS.Find(id);
            db.MARKS.Remove(mark);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            var mrk = db.MARKS.Find(id);
            return View("Update", mrk);
        }

        [HttpPost]
        public ActionResult Update(Class1 model, MARKS p, int EXAM1 = 0, int EXAM2 = 0, int EXAM3 = 0, int PROJECT = 0)
        {
            if(model.operation == "Calculate")
            {
                float AVERAGE = (EXAM1 + EXAM2 + EXAM3 + PROJECT) / 4;
                ViewBag.avg = AVERAGE;
                
                if(AVERAGE < 50)
                {
                    ViewBag.sit = false;
                }
                else
                {
                    ViewBag.sit = true;
                }
            }
            else if(model.operation == "Update")
            {
                var mrk = db.MARKS.Find(p.MARKID);
                mrk.STDID = p.STDID;
                mrk.LECTUREID = p.LECTUREID;
                mrk.EXAM1 = p.EXAM1;
                mrk.EXAM2 = p.EXAM2;
                mrk.EXAM3 = p.EXAM3;
                mrk.PROJECT = p.PROJECT;
                mrk.AVERAGE = p.AVERAGE;
                mrk.SITUATION = p.SITUATION;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Student-Management-System/Views/Mark/Index.cshtml
@using StudentManagementSystem.Models.EntityFramework
@model List<MARKS>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th style="text-align:center" bgcolor="LightBlue">MARK ID</th>
        <th style="text-align:center" bgcolor="LightBlue">STUDENT NAME</th>
        <th style="text-align:center" bgcolor="LightBlue">STUDENT SURNAME</th>
        <th style="text-align:center" bgcolor="LightBlue">LECTURE NAME</th>
        <th style="text-align:center" bgcolor="LightBlue">EXAM 1</th>
        <th style="text-align:center" bgcolor="LightBlue">EXAM 2</th>
        <th style="text-align:center" bgcolor="LightBlue">EXAM 3</th>
        <th style="text-align:center" bgcolor="LightBlue">PROJECT</th>
        <th style="text-align:center" bgcolor="LightBlue">AVERAGE</th>
        <th style="text-align:center" bgcolor="LightBlue">SITUATION</th>
        <th style="text-align:center" bgcolor="LightBlue">OPERATIONS</th>
    </tr>
    <tbody>
        @foreach (var mark in Model)
        {
            <tr>
                <td style="text-align:center" bgcolor="white">@mark.MARKID</td>
                <td style="text-align:center" bgcolor="white">@mark.STUDENTS.STDNAME</td>
                <td style="text-align:center" bgcolor="white">@mark.STUDENTS.STDSURNAME</td>
                <td style="text-align:center" bgcolor="white">@mark.LECTURES.LECTURENAME</td>
                <td style="text-align:center" bgcolor="white">@mark.EXAM1</td>
                <td style="text-align:center" bgcolor="white">@mark.EXAM2</td>
                <td style="text-align:center" bgcolor="white">@mark.EXAM3</td>
                <td style="text-align:center" bgcolor="white">@mark.PROJECT</td>
                <td style="text-align:center" bgcolor="white">@mark.AVERAGE</td>
                <td style="text-align:center" bgcolor="white">@mark.SITUATION</td>
                <td style="text-align:center" bgcolor="white">
                    <a href="/Mark/Update/@mark.MARKID" class="btn btn-warning">Update</a>
                    <a href="/Mark/Delete/@mark.MARKID" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }

    </tbody>
</table>
<a href="/Mark/NewMark" class="btn btn-primary">Add a New Mark</a>

Student-Management-System/Views/Mark/NewMark.cshtml
@{
    ViewBag.Title = "NewMark";
}

<form method="post" class="form-group">
    <div>
        <label class="text-warning">STUDENT ID</label>
        <input type="text" class="form-control" name="STDID" />
    </div>

    <div style="margin-top:10px">
        <label class="text-warning">LECTURE ID</label>
        <input type="text" class="form-control" name="LECTUREID" />
    </div>

    <div style="margin-top:10px">
        <label class="text-warning">EXAM 1</label>
        <input type="text" class="form-control" name="EXAM1" />
    </div>

    <div style="margin-top:10px">
        <label class="text-warning">EXAM 2</label>
        <input type="text" class="form-control" name="EXAM2" />
    </div>

    <div style="margin-top:10px">
        <label class="text-warning">EXAM 3</label>
        <input type="text" class="form-control" name="EXAM3" />
    </div>

    <div style="margin-top:10px">
        <label class="text-warning">PROJECT</label>
        <input type="text" class="form-control" name="PROJECT" />
    </div>

    <div style="margin-top:10px">
        <label class="text-warning">AVERAGE</label>
        <input type="text" class="form-control" name="AVERAGE" />
    </div>

    <div style="margin-top:10px">
        <label class="text-warning">SITUATION</label>
        <input type="text" class="form-control" name="SITUATION" />
    </div>

    <div style="margin-top:10px">
        <button class="btn btn-success">Add Mark</button>
    </div>
</form>

Student-Management-System/Views/Mark/Update.cshtml
@model StudentManagementSystem.Models.EntityFramework.MARKS
@{
    ViewBag.Title = "Update";
}

@using (Html.BeginForm("Update", "Mark", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.STDID, new { @class = "text-warning" })
        @Html.TextBoxFor(m => m.STDID, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.LECTUREID, new { @class = "text-warning" })
        @Html.TextBoxFor(m => m.LECTUREID, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.EXAM1, new { @class = "text-warning" })
        @Html.TextBoxFor(m => m.EXAM1, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.EXAM2, new { @class = "text-warning" })
        @Html.TextBoxFor(m => m.EXAM2, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.EXAM3, new { @class = "text-warning" })
        @Html.TextBoxFor(m => m.EXAM3, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.PROJECT, new { @class = "text-warning" })
        @Html.TextBoxFor(m => m.PROJECT, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.AVERAGE, new { @class = "text-warning" })
        @Html.TextBoxFor(m => m.AVERAGE, new {@Value = ViewBag.avg, @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.SITUATION, new { @class = "text-warning" })
        @Html.TextBoxFor(m => m.SITUATION, new { @Value = @ViewBag.sit, @class = "form-control" })
    </div>

    @Html.HiddenFor(m => m.MARKID)
    <div style="margin-top:15px">
        <button type="submit" name="operation" value="Calculate" class="btn btn-success">
            Calculate
        </button>
    </div>

    <div style="margin-top:15px">
        <button type="submit" name="operation" value="Update" class="btn btn-warning">
            Update
        </button>
    </div>
}