Student-Management-System/Models/EntityFramework/LECTURES.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LECTURES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LECTURES()
        {
            this.MARKS = new HashSet<MARKS>();
        }
    
        public byte LECTUREID { get; set; }
        public string LECTURENAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARKS> MARKS { get; set; }
    }
}

Student-Management-System/Controllers/LectureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentManagementSystem.Models.EntityFramework;

namespace StudentManagementSystem.Controllers
{
    public class LectureController : Controller
    {
        // GET: Lecture
        DbSchoolEntities db = new DbSchoolEntities();
        public ActionResult Index()
        {
            var lectures = db.LECTURES.ToList();
            return View(lectures);
        }
        [HttpGet]
        public ActionResult AddNewLecture()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddNewLecture(LECTURES p)
        {
            db.LECTURES.Add(p);
            db.SaveChanges();
            return View();
        }

        public ActionResult Delete(int id)
        {
            var lct = db.LECTURES.Find(id);
            db.LECTURES.Remove(lct);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Update(int id)
        {
            var lecture = db.LECTURES.Find(id);
            return View("Update",lecture);
        }
        public ActionResult LectureUpdate(LECTURES p)
        {
            var lecture = db.LECTURES.Find(p.LECTUREID);
            lecture.LECTURENAME = p.LECTURENAME;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Student-Management-System/Views/Lecture/AddNewLecture.cshtml
@{
    ViewBag.Title = "AddNewLecture";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" class="form-group">
    <div>
        <label class="text-warning">LECTURE NAME</label>
        <input type="text" class="form-control" name="LECTURENAME" />
    </div>
    <div style="margin-top:10px">
        <button class="btn btn-success">Add</button>
    </div>
</form>

Student-Management-System/Views/Lecture/Index.cshtml
@using StudentManagementSystem.Models.EntityFramework
@model List<LECTURES>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<table class="table table-bordered">
    <tr>
        <th style="text-align:center" bgcolor="LightBlue">LECTURE ID</th>
        <th style="text-align:center" bgcolor="LightBlue">LECTURE NAME</th>
        <th style="text-align:center" bgcolor="LightBlue">OPERATIONS</th>
    </tr>
    <tbody>
        @foreach (var lecture in Model)
        {
        <tr>
            <td style="text-align:center" bgcolor="white">@lecture.LECTUREID</td>
            <td style="text-align:center" bgcolor="white">@lecture.LECTURENAME</td>
            <td style="text-align:center" bgcolor="white">
                <a href="/Lecture/Delete/@lecture.LECTUREID" class="btn btn-danger">Delete</a>
                <a href="/Lecture/Update/@lecture.LECTUREID" class="btn btn-warning">Update</a>
            </td>
        </tr>
        }
    </tbody>
</table>
<a href="/Lecture/AddNewLecture" class="btn btn-primary">Add New Lecture</a>

Student-Management-System/Views/Lecture/Update.cshtml
@model StudentManagementSystem.Models.EntityFramework.LECTURES
@{
    ViewBag.Title = "Update";
}

@using (Html.BeginForm("LectureUpdate", "Lecture", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m=>m.LECTURENAME, new { @class = "text-warning" })
        @Html.TextBoxFor(m=>m.LECTURENAME, new { @class="form-control"})
    </div>
    @Html.HiddenFor(m=>m.LECTUREID)
    <div style="margin-top:15px">
        <button class="btn btn-success">Update</button>
    </div>
}