Student-Management-System/Models/EntityFramework/CLUBS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLUBS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLUBS()
        {
            this.STUDENTS = new HashSet<STUDENTS>();
        }
    
        public byte CLUBID { get; set; }
        public string CLUBNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENTS> STUDENTS { get; set; }
    }
}

Student-Management-System/Controllers/ClubController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentManagementSystem.Models.EntityFramework;

namespace StudentManagementSystem.Controllers
{
    public class ClubController : Controller
    {
        // GET: Club
        DbSchoolEntities db = new DbSchoolEntities();
        public ActionResult Index()
        {
            var clb = db.CLUBS.ToList();
            return View(clb);
        }

        [HttpGet]
        public ActionResult AddNewClub()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddNewClub(CLUBS p)
        {
            db.CLUBS.Add(p);
            db.SaveChanges();
            return View();
        }

        public ActionResult Delete(int id)
        {
            var club = db.CLUBS.Find(id);
            db.CLUBS.Remove(club);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Update(int id)
        {
            var clb = db.CLUBS.Find(id);
            return View("Update",clb);
        }

        public ActionResult ClubUpdate(CLUBS p)
        {
            var clb = db.CLUBS.Find(p.CLUBID);
            clb.CLUBNAME = p.CLUBNAME;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Student-Management-System/Views/Club/AddNewClub.cshtml
@{
    ViewBag.Title = "AddNewClub";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" class="form-group">
    <div>
        <label class="text-warning">CLUB NAME</label>
        <input type="text" class="form-control" name="CLUBNAME" />
    </div>
    <div style="margin-top:10px">
        <button class="btn btn-success">Add</button>
    </div>
</form>

Student-Management-System/Views/Club/Index.cshtml
@using StudentManagementSystem.Models.EntityFramework
@model List<CLUBS>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th style="text-align:center" bgcolor="LightBlue">CLUB ID</th>
        <th style="text-align:center" bgcolor="LightBlue">CLUB NAME</th>
        <th style="text-align:center" bgcolor="LightBlue">OPERATIONS</th>
    </tr>
    <tbody>
        @foreach (var clb in Model)
        {
            <tr>
                <td style="text-align:center" bgcolor="white">@clb.CLUBID</td>
                <td style="text-align:center" bgcolor="white">@clb.CLUBNAME</td>
                <td style="text-align:center" bgcolor="white">
                    <a href="/Club/Delete/@clb.CLUBID" class="btn btn-danger">Delete</a>
                    <a href="/Club/Update/@clb.CLUBID" class="btn btn-warning">Update</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a href="/Club/AddNewClub" class="btn btn-primary">Add New Club</a>

Student-Management-System/Views/Club/Update.cshtml
@model StudentManagementSystem.Models.EntityFramework.CLUBS
@{
    ViewBag.Title = "Update";
}

@using (Html.BeginForm("ClubUpdate", "Club", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.CLUBNAME, new { @class = "text-warning" })
        @Html.TextBoxFor(m => m.CLUBNAME, new { @class="form-control" })
    </div>
    @Html.HiddenFor(m => m.CLUBID)
    <div style="margin-top:15px">
        <button class="btn btn-success">Update</button>
    </div>
}